export const SERVICES_FETCH_REQUESTED = 'SERVICES_FETCH_REQUESTED';
export const SERVICES_FETCH_SUCCESSED = 'SERVICES_FETCH_SUCCESSED';
export const SERVICES_FETCH_FAILED = 'SERVICES_FETCH_FAILED';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

